Yayy!! This is a binary classification problem

Shit! This is imbalanced classification also.

In [5]:
import pandas as pd
import numpy as np
import zipfile 
import os

In [6]:
pd.set_option('display.max_columns', 1000)

In [7]:
pd.set_option('display.max_rows', 10000)

In [8]:
with open('train_iI26erW/train.csv', 'r') as fp, open('test_plBmD8c.csv') as fg:
    train = pd.read_csv(fp)
    test = pd.read_csv(fg)

/home/manish/anaconda2/envs/py35/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (8,11,12,13,14,15,16,17,18,19,21,23,26,28,29,30,32,82,83,85,91,269,325,326,327,328) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/home/manish/anaconda2/envs/py35/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (8,11,12,13,14,15,16,17,18,19,26,28,29,30,82,83,85,91,269,325,326,327,328) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [51]:
train.shape

(300000, 128)

In [16]:
train.head()

,CUSTOMER_ID,ACT_TYPE,GENDER,LEGAL_ENTITY,OCCUP_ALL_NEW,AGE,N_CASA_MAX_BALANCE_MTD,N_CASA_MIN_BALANCE_MTD,BL_TAG,TWL_TAG,PL_TAG,AL_CNC_TAG,AGRI_TAG,CE_TAG,CV_TAG,EDU_TAG,TL_TAG,OTHER_LOANS_TAG,LAP_TAG,LAS_TAG,EEG_TAG,BBG_TAG,HL_TAG,GL_TAG,AL_CLOSED,PL_CLOSED,BL_CLOSED,TWL_CLOSED,CV_CLOSED,LAP_CLOSED,LAS_CLOSED,EEG_CLOSED,BBG_CLOSED,GL_CLOSED,CC_HOLD_MON_03,CC_HOLD_MON_02,CC_HOLD_MON_01,CC_ACTIVE_MON_03,CC_ACTIVE_MON_02,CC_ACTIVE_MON_01,CC_HOLD,CC_ACTIVE,DC_HOLD,DC_ACTIVE_MON_03,DC_ACTIVE_MON_02,DC_ACTIVE_MON_01,DC_ACTIVE,DC_SPEND_MON_03,DC_SPEND_MON_02,DC_SPEND_MON_01,CC_SPEND_MON_04,CC_SPEND_MON_01,CC_SPEND_MON_02,CC_SPEND_MON_03,DC_SPEND_MON_04,PM_FD_MON_01,PM_FD_MON_02,PM_FD_MON_04,CR_LIMIT,STMT_MON_03,STMT_MON_02,STMT_MON_01,COC_ELIGIBLE,LAP_SCRUB_LIVE,LAS_SCRUB_LIVE,PL_SCRUB_LIVE,GL_SCRUB_LIVE,TWL_SCRUB_LIVE,BL_SCRUB_LIVE,CEL_SCRUB_LIVE,TL_SCRUB_LIVE,AL_SCRUB_LIVE,LAP_SCRUB_CLOSED,LAS_SCRUB_CLOSED,PL_SCRUB_CLOSED,GL_SCRUB_CLOSED,TWL_SCRUB_CLOSED,BL_SCRUB_CLOSED,CEL_SCRUB_CLOSED,TL_SCRUB_CLOSED,AL_SCRUB_CLOSED,MATURITY_GL,MATURITY_LAP,MATURITY_LAS,STMT_CON_DAE_ACTIVE_MON_01,BTE_ACTIVE_MON_01,COC_ACTIVE_MON_01,PL2CC_ACTIVE_MON_01,MER_EMI_ACTIVE_MON_01,TRN_CON_DAE_ACTIVE_MON_01,STMT_CON_DAE_CLOSED_MON_01,BTE_CLOSED_MON_01,COC_CLOSED_MON_01,PL2CC_CLOSED_MON_01,MER_EMI_CLOSED_MON_01,TRN_CON_DAE_CLOSED_MON_01,EOP_BAL_MON_01,AMB_MON_04,AMB_MON_01,AMB_MON_02,AMB_MON_03,NB_MON_01_CNT,NB_MON_02_CNT,NB_MON_03_CNT,CDMAT_MON_01,CDMAT_MON_04,MF_MON_04,MF_MON_01,RD_MON_04,RD_MON_01,FD_MON_04,FD_MON_01,LI_MON_04,LI_MON_01,GI_MON_04,GI_MON_01,CC_TXN_MON_01,CC_SPEND_MON_06,CC_TXN_MON_06,CC_TXN_MON_03,CC_TXN_MON_02,CC_TXN_MON_04,CC_SPEND_MON_05,CC_TXN_MON_05,DC_TXN_MON_04,DC_TXN_MON_01,DC_SPEND_MON_06,DC_TXN_MON_06,DC_SPEND_MON_05,DC_TXN_MON_05,DC_TXN_MON_03,DC_TXN_MON_02,DC_SPEND_MON_04_ENT,DC_SPEND_MON_04_MED,DC_SPEND_MON_04_GRC,DC_SPEND_MON_04_HMD,DC_SPEND_MON_04_HBY,DC_SPEND_MON_04_CARE,DC_SPEND_MON_04_TRL,DC_SPEND_MON_04_RST,DC_SPEND_MON_04_JER,DC_SPEND_MON_04_HTL,DC_SPEND_MON_04_ATM,DC_SPEND_MON_03_ENT,DC_SPEND_MON_03_MED,DC_SPEND_MON_03_HMD,DC_SPEND_MON_03_HBY,DC_SPEND_MON_03_CARE,DC_SPEND_MON_03_TRL,DC_SPEND_MON_03_RST,DC_SPEND_MON_03_JER,DC_SPEND_MON_03_HTL,DC_SPEND_MON_03_ATM,DC_SPEND_MON_02_ENT,DC_SPEND_MON_02_MED,DC_SPEND_MON_02_HMD,DC_SPEND_MON_02_HBY,DC_SPEND_MON_02_CARE,DC_SPEND_MON_02_TRL,DC_SPEND_MON_02_RST,DC_SPEND_MON_02_JER,DC_SPEND_MON_02_HTL,DC_SPEND_MON_02_ATM,DC_SPEND_MON_01_ENT,DC_SPEND_MON_01_MED,DC_SPEND_MON_01_HMD,DC_SPEND_MON_01_HBY,DC_SPEND_MON_01_CARE,DC_SPEND_MON_01_TRL,DC_SPEND_MON_01_RST,DC_SPEND_MON_01_JER,DC_SPEND_MON_01_HTL,DC_SPEND_MON_01_ATM,DC_SPEND_MON_05_ENT,DC_SPEND_MON_05_MED,DC_SPEND_MON_05_HMD,DC_SPEND_MON_05_HBY,DC_SPEND_MON_05_CARE,DC_SPEND_MON_05_TRL,DC_SPEND_MON_05_RST,DC_SPEND_MON_05_JER,DC_SPEND_MON_05_HTL,DC_SPEND_MON_05_ATM,CC_SPEND_MON_04_ENT,CC_SPEND_MON_04_MED,CC_SPEND_MON_04_HMD,CC_SPEND_MON_04_HBY,CC_SPEND_MON_04_CARE,CC_SPEND_MON_04_TRL,CC_SPEND_MON_04_RST,CC_SPEND_MON_04_JER,CC_SPEND_MON_04_HTL,CC_SPEND_MON_04_ATM,CC_SPEND_MON_02_ENT,CC_SPEND_MON_02_MED,CC_SPEND_MON_02_HMD,CC_SPEND_MON_02_HBY,CC_SPEND_MON_02_CARE,CC_SPEND_MON_02_TRL,CC_SPEND_MON_02_RST,CC_SPEND_MON_02_JER,CC_SPEND_MON_02_HTL,CC_SPEND_MON_02_ATM,CC_SPEND_MON_01_ENT,CC_SPEND_MON_01_MED,CC_SPEND_MON_01_HMD,CC_SPEND_MON_01_HBY,CC_SPEND_MON_01_CARE,CC_SPEND_MON_01_TRL,CC_SPEND_MON_01_RST,CC_SPEND_MON_01_JER,CC_SPEND_MON_01_HTL,CC_SPEND_MON_01_ATM,FINANCE_MON_01,JOBS_MON_01,LIFESTYLE_MON_01,INMON_01KET_MON_01,TRAVEL_MON_01,CHANNEL_CLICK_DISP,DESIGNATION_FINAL,TOP14_CITY,TOP9_CITY,PL2CC_ELIGIBLE,D_AMT_L3_MON_06,C_AMT_L3_MON_06,C_COUNT_L3_MON_06,D_COUNT_L3_MON_06,MAX_C_AMT_L3_MON_06,D_AMT_L3_MON_05,C_AMT_L3_MON_05,C_COUNT_L3_MON_05,D_COUNT_L3_MON_05,MAX_C_AMT_L3_MON_05,D_AMT_L3_MON_04,C_AMT_L3_MON_04,C_COUNT_L3_MON_04,D_COUNT_L3_MON_04,MAX_C_AMT_L3_MON_04,D_AMT_L3_MON_03,C_AMT_L3_MON_03,C_COUNT_L3_MON_03,D_COUNT_L3_MON_03,MAX_C_AMT_L3_MON_03,D_AMT_L3_MON_02,C_AMT_L3_MON_02,C_COUNT_L3_MON_02,D_COUNT_L3_MON_02,MAX_C_AMT_L3_MON_02,D_AMT_L3_MON_01,C_AMT_L3_MON_01,C_COUNT_L3_MON_01,D_COUNT_L3_MON_01,MAX_C_AMT_L3_MON_01,PA_PQ_TAG,NEFT_CC_AMOUNT,NEFT_CC_TXN,NEFT_CC_CATEGORY,NEFT_DC_AMOUNT,NEFT_DC_TXN,NEFT_DC_CATEGORY,TPT_DC_AMOUNT_MON_01,TPT_DC_TXN_MON_01,TPT_DC_CATEGORY_MON_01,TPT_CC_AMOUNT_MON_01,TPT_CC_TXN_MON_01,TPT_CC_CATEGORY_MON_01,IMPS_CC_AMOUNT_MON_01,IMPS_CC_TXN_MON_01,IMPS_CC_CATEGORY_MON_01,ZIP_CODE_FINAL,LAST_3MTHS_INQ,PREV_3MTHS_INQ,CAR_MON_03,CDL_MON_03,GL_MON_03,LAA_MON_03,LFP_MON_03,TWL_MON_03,PL_MON_03,CAR_MON_02,CDL_MON_02,GL_MON_02,LAA_MON_02,LFP_MON_02,TWL_MON_02,PL_MON_02,CAR_MON_01,CDL_MON_01,GL_MON_01,LAA_MON_01,LFP_MON_01,TWL_MON_01,PL_MON_01,CLOSED_DATE,CRED_NEED_SCORE,CC_SPEND_MON_03_ENT,CC_SPEND_MON_03_MED,CC_SPEND_MON_03_HMD,CC_SPEND_MON_03_HBY,CC_SPEND_MON_03_CARE,CC_SPEND_MON_03_TRL,CC_SPEND_MON_03_RST,CC_SPEND_MON_03_JER,CC_SPEND_MON_03_HTL,CC_SPEND_MON_03_ATM,CARD_AUTOMOBILE_MON_01,CARD_HOTEL_MON_01,CARD_JEWELLERY_MON_01,CARD_RESTAURANT_MON_01,CARD_TRAVEL_MON_01,CARD_PRSNL_CARE_MON_01,CARD_HOBBY_MON_01,CARD_HOME_DECOR_MON_01,CARD_MEDICAL_MON_01,CARD_ENTMNT_MON_01,SAL_MON_01,SAL_MON_02,SAL_MON_03,TOP_100_CORP,TOP_800_CORP,TOP_CORP_TAG,EOP_MON_02,EOP_MON_03,CREDIT_ACT,DEBIT_ACT,CEL_TAG,EL_TAG,AGL_TAG,CVL_TAG,AL_TAG,HL_EMI,SCRUB_EMI,RESPONDERS
0,385793,CSA,M,INDIVIDUAL,SALARIED,21,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,Y,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,NONE,MISSING,Y,Y,0,39.00,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO_NEFT_TXN,NaN,NaN,NO_NEFT_TXN,NaN,NaN,NO_TPT_TXN,NaN,NaN,NO_TPT_TXN,NaN,NaN,NO_IMPS_TXN,400606.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,N,N,N,N,0.0,0.0,0.0,NaN,NaN,NONE,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,N
1,286891,CSA,M,INDIVIDUAL,SALARIED,23,8243.77,7.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,Y,Y,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.77,1417.26,300.51,593.06,418.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,5.0,504.0,7.0,631.0,13.0,12.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,NONE,MISSING,Y,Y,0,17250.00,17870.00,3.0,19.0,7957.0,12965.50,12336.5,6.0,21.0,8011.0,23448.52,23457.0,4.0,12.0,12000.0,17161.73,17154.75,6.0,20.0,8144.0,8720.00,11733.75,4.0,3.0,7519.0,13763.00,10758.00,3.0,9.0,8240.0,NaN,NaN,NaN,NO_NEFT_TXN,NaN,NaN,NO_NEFT_TXN,NaN,NaN,NO_TPT_TXN,NaN,NaN,NO_TPT_TXN,NaN,NaN,NO_IMPS_TXN,600045.0,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,N,N,N,N,10754.0,8733.0,17154.0,NaN,NaN,NONE,3016.77,3.02,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,N
2,108751,CSA,M,INDIVIDUAL,SALARIED,41,26515.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,Y,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26458.25,5354.65,6100.73,7955.82,11138.53,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,Y,NONE,MISSING,N,N,0,39362.25,39125.00,2.0,8.0,28171.0,2005.75,31261.0,3.0,2.0,16171.0,29064.00,16197.0,2.0,3.0,16171.0,8727.25,7180.00,2.0,3.0,4680.0,36375.75,31516.00,2.0,4.0,16516.0,28520.75,44980.00,5.0,3.0,16516.0,NaN,NaN,NaN,NO_NEFT_TXN,26515.0,1.0,NOT_RELEVANT,NaN,NaN,NO_TPT_TXN,NaN,NaN,NO_TPT_TXN,NaN,NaN,NO_IMPS_TXN,122001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,N,N,N,N,0.0,0.0,0.0,NaN,NaN,NONE,9999.00,14858.75,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,N
3,278651,CSA,M,INDIVIDUAL,SALARIED,28,65917.28,8270.28,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,Y,Y,NaN,Y,Y,Y,Y,Y,Y,Y,Y,10960.0,795.0,NaN,6782.0,NaN,NaN,22713.22,5340.0,NaN,NaN,NaN,62000.0,6051.22,22681.82,0.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65917.28,113120.39,35560.81,42686.93,61593.38,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,10935.00,5.0,15.0,NaN,9.0,803.00,4.0,2.0,6.0,NaN,NaN,1531.0,2.0,9.0,12.0,NaN,NaN,1330.0,NaN,5340.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2900.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8790.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,N,N,N,N,NONE,MISSING,N,N,0,128169.25,20152.03,2.0,20.0,19840.0,52325.00,19840.0,1.0,8.0,19840.0,69002.00,21526.0,2.0,9.0,19840.0,75750.25,19605.00,1.0,18.0,19605.0,37712.17,15200.00,1.0,17.0,15200.0,47158.82,85913.00,4.0,11.0,46500.0,NaN,NaN,NaN,NO_NEFT_TXN,NaN,NaN,NO_NEFT_TXN,NaN,NaN,NO_TPT_TXN,NaN,NaN,NO_TPT_TXN,NaN,NaN,NO_IMPS_TXN,311408.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.247852,NaN,NaN,2558.0,NaN,NaN,NaN,NaN,8200.0,NaN,NaN,N,N,Y,N,N,Y,N,Y,Y,N,38952.0,15200.0,19605.0,NaN,NaN,NONE,27163.10,49675.27,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,N
4,23637,CSA,M,INDIVIDUAL,SALARIED,34,22260.94,6060.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,Y,Y,Y,Y,Y,Y,Y,NaN,NaN,NaN,N,NaN,NaN,NaN,1199.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88000.0,15660.04,21246.48,16483.54,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,Y,NaN,NaN,NaN,Y,Y,NaN,Y,6172.94,9099.94,15858.71,14008.08,4570.73,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,15094.78,21.0,16.0,7.0,16.0,8333.35,13.0,NaN,NaN,NaN,NaN,380.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,380.0,NaN,NaN,NaN,NaN,NaN,NaN,1199.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7776.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,NONE,ENGINEER,N,N,0,18668.96,24565.91,4.0,7.0,14000.0,26931.60,29500.0,3.0,7.0,21500.0,13700.00,9264.0,4.0,1.0,5000.0,9817.25,6532.79,4.0,3.0,3580.0,37936.00,58018.00,4.0,5.0,29000.0,16200.00,1307.07,4.0,1.0,690.0,PQ_WITH_INCOME_20K,NaN,NaN,NO_NEFT_TXN,NaN,NaN,NO_NEFT_TXN,NaN,NaN,NO_TPT_TXN,NaN,NaN,NO_TPT_TXN,200.0,1.0,NOT_RELEVANT,122015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,N,N,N,Y,N,0.0,0.0,0.0,NaN,NaN,NONE,21065.87,983.87,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,251.758794,N

In [18]:
train['RESPONDERS'].value_counts(normalize=True)

N    0.984627
Y    0.015373
Name: RESPONDERS, dtype: float64

In [12]:
test.head()

,CUSTOMER_ID,ACT_TYPE,GENDER,LEGAL_ENTITY,OCCUP_ALL_NEW,AGE,N_CASA_MAX_BALANCE_MTD,N_CASA_MIN_BALANCE_MTD,BL_TAG,TWL_TAG,...,EOP_MON_03,CREDIT_ACT,DEBIT_ACT,CEL_TAG,EL_TAG,AGL_TAG,CVL_TAG,AL_TAG,HL_EMI,SCRUB_EMI
0,15800,CSA,M,INDIVIDUAL,SALARIED,35,1280.74,1197.74,NaN,NaN,...,17697.74,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2557.670455
1,463196,CSA,M,INDIVIDUAL,SALARIED,27,8375.36,59.36,NaN,NaN,...,1377.99,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,1744.382609
2,309959,SA,F,INDIVIDUAL,SALARIED,37,42.00,42.00,NaN,NaN,...,42.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
3,102348,CSA,F,INDIVIDUAL,SALARIED,31,0.00,0.00,NaN,NaN,...,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
4,114850,CSA,F,INDIVIDUAL,SALARIED,28,207084.79,0.00,NaN,NaN,...,216580.99,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2220.316265

In [13]:
np.setdiff1d(train.columns, test.columns)

array(['RESPONDERS'], dtype=object)

### Make submission

In [28]:
sub = pd.DataFrame({'CUSTOMER_ID':test['CUSTOMER_ID'], 'RESPONDERS':0.0011111})

In [27]:
sub.to_csv('submissions/sub1.csv', index=False) #0.1027

In [29]:
sub.to_csv('submissions/sub2.csv', index=False)  # 0.1027

### Model 2 - XGB

In [9]:
## check missing values

misCols = train.isnull().sum(axis=0)/train.shape[0]

In [10]:
## drop columns with 90% missing values
toremove = []

for k, v in misCols.iteritems():
    if v >= 0.9:
        toremove.append(k)

In [11]:
train.drop(toremove, inplace=True, axis=1)
test.drop(toremove, inplace=True, axis=1)

In [93]:
train.head()

,CUSTOMER_ID,ACT_TYPE,GENDER,LEGAL_ENTITY,OCCUP_ALL_NEW,AGE,N_CASA_MAX_BALANCE_MTD,N_CASA_MIN_BALANCE_MTD,CC_HOLD_MON_03,CC_HOLD_MON_02,CC_HOLD_MON_01,CC_ACTIVE_MON_03,CC_ACTIVE_MON_02,CC_ACTIVE_MON_01,CC_HOLD,CC_ACTIVE,DC_HOLD,DC_ACTIVE_MON_03,DC_ACTIVE_MON_02,DC_ACTIVE_MON_01,DC_ACTIVE,DC_SPEND_MON_03,DC_SPEND_MON_02,DC_SPEND_MON_01,DC_SPEND_MON_04,CR_LIMIT,STMT_MON_03,STMT_MON_02,STMT_MON_01,COC_ELIGIBLE,EOP_BAL_MON_01,AMB_MON_04,AMB_MON_01,AMB_MON_02,AMB_MON_03,NB_MON_01_CNT,NB_MON_02_CNT,NB_MON_03_CNT,CC_TXN_MON_01,CC_SPEND_MON_06,CC_TXN_MON_06,CC_TXN_MON_03,CC_TXN_MON_02,CC_TXN_MON_04,CC_SPEND_MON_05,CC_TXN_MON_05,DC_TXN_MON_04,DC_TXN_MON_01,DC_SPEND_MON_06,DC_TXN_MON_06,DC_SPEND_MON_05,DC_TXN_MON_05,DC_TXN_MON_03,DC_TXN_MON_02,DC_SPEND_MON_04_GRC,DC_SPEND_MON_04_RST,FINANCE_MON_01,JOBS_MON_01,LIFESTYLE_MON_01,INMON_01KET_MON_01,TRAVEL_MON_01,CHANNEL_CLICK_DISP,DESIGNATION_FINAL,TOP14_CITY,TOP9_CITY,PL2CC_ELIGIBLE,D_AMT_L3_MON_06,C_AMT_L3_MON_06,C_COUNT_L3_MON_06,D_COUNT_L3_MON_06,MAX_C_AMT_L3_MON_06,D_AMT_L3_MON_05,C_AMT_L3_MON_05,C_COUNT_L3_MON_05,D_COUNT_L3_MON_05,MAX_C_AMT_L3_MON_05,D_AMT_L3_MON_04,C_AMT_L3_MON_04,C_COUNT_L3_MON_04,D_COUNT_L3_MON_04,MAX_C_AMT_L3_MON_04,D_AMT_L3_MON_03,C_AMT_L3_MON_03,C_COUNT_L3_MON_03,D_COUNT_L3_MON_03,MAX_C_AMT_L3_MON_03,D_AMT_L3_MON_02,C_AMT_L3_MON_02,C_COUNT_L3_MON_02,D_COUNT_L3_MON_02,MAX_C_AMT_L3_MON_02,D_AMT_L3_MON_01,C_AMT_L3_MON_01,C_COUNT_L3_MON_01,D_COUNT_L3_MON_01,MAX_C_AMT_L3_MON_01,PA_PQ_TAG,NEFT_CC_AMOUNT,NEFT_CC_TXN,NEFT_CC_CATEGORY,NEFT_DC_AMOUNT,NEFT_DC_TXN,NEFT_DC_CATEGORY,TPT_DC_CATEGORY_MON_01,TPT_CC_CATEGORY_MON_01,IMPS_CC_CATEGORY_MON_01,ZIP_CODE_FINAL,CRED_NEED_SCORE,CARD_AUTOMOBILE_MON_01,CARD_HOTEL_MON_01,CARD_JEWELLERY_MON_01,CARD_RESTAURANT_MON_01,CARD_TRAVEL_MON_01,CARD_PRSNL_CARE_MON_01,CARD_HOBBY_MON_01,CARD_HOME_DECOR_MON_01,CARD_MEDICAL_MON_01,CARD_ENTMNT_MON_01,SAL_MON_01,SAL_MON_02,SAL_MON_03,TOP_CORP_TAG,EOP_MON_02,EOP_MON_03,CREDIT_ACT,DEBIT_ACT,SCRUB_EMI,RESPONDERS
0,385793,CSA,M,INDIVIDUAL,SALARIED,21,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,N,N,Y,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,NONE,MISSING,Y,Y,0,39.00,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO_NEFT_TXN,NaN,NaN,NO_NEFT_TXN,NO_TPT_TXN,NO_TPT_TXN,NO_IMPS_TXN,400606.0,NaN,N,N,N,N,N,N,N,N,N,N,0.0,0.0,0.0,NONE,0.00,0.00,NaN,NaN,0.000000,N
1,286891,CSA,M,INDIVIDUAL,SALARIED,23,8243.77,7.77,NaN,NaN,NaN,NaN,NaN,NaN,N,N,Y,Y,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,11.77,1417.26,300.51,593.06,418.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,5.0,504.0,7.0,631.0,13.0,12.0,1.0,NaN,NaN,N,N,N,N,N,NONE,MISSING,Y,Y,0,17250.00,17870.00,3.0,19.0,7957.0,12965.50,12336.5,6.0,21.0,8011.0,23448.52,23457.0,4.0,12.0,12000.0,17161.73,17154.75,6.0,20.0,8144.0,8720.00,11733.75,4.0,3.0,7519.0,13763.00,10758.00,3.0,9.0,8240.0,NaN,NaN,NaN,NO_NEFT_TXN,NaN,NaN,NO_NEFT_TXN,NO_TPT_TXN,NO_TPT_TXN,NO_IMPS_TXN,600045.0,NaN,N,N,N,N,N,N,N,N,N,N,10754.0,8733.0,17154.0,NONE,3016.77,3.02,Y,Y,0.000000,N
2,108751,CSA,M,INDIVIDUAL,SALARIED,41,26515.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,N,N,Y,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,26458.25,5354.65,6100.73,7955.82,11138.53,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,Y,NONE,MISSING,N,N,0,39362.25,39125.00,2.0,8.0,28171.0,2005.75,31261.0,3.0,2.0,16171.0,29064.00,16197.0,2.0,3.0,16171.0,8727.25,7180.00,2.0,3.0,4680.0,36375.75,31516.00,2.0,4.0,16516.0,28520.75,44980.00,5.0,3.0,16516.0,NaN,NaN,NaN,NO_NEFT_TXN,26515.0,1.0,NOT_RELEVANT,NO_TPT_TXN,NO_TPT_TXN,NO_IMPS_TXN,122001,NaN,N,N,N,N,N,N,N,N,N,N,0.0,0.0,0.0,NONE,9999.00,14858.75,Y,Y,0.000000,N
3,278651,CSA,M,INDIVIDUAL,SALARIED,28,65917.28,8270.28,Y,Y,Y,Y,NaN,Y,Y,Y,Y,Y,Y,Y,Y,10960.0,795.0,NaN,5340.0,62000.0,6051.22,22681.82,0.00,1,65917.28,113120.39,35560.81,42686.93,61593.38,1.0,1.0,1.0,3.0,10935.00,5.0,15.0,NaN,9.0,803.00,4.0,2.0,6.0,NaN,NaN,1531.0,2.0,9.0,12.0,1330.0,NaN,Y,N,N,N,N,NONE,MISSING,N,N,0,128169.25,20152.03,2.0,20.0,19840.0,52325.00,19840.0,1.0,8.0,19840.0,69002.00,21526.0,2.0,9.0,19840.0,75750.25,19605.00,1.0,18.0,19605.0,37712.17,15200.00,1.0,17.0,15200.0,47158.82,85913.00,4.0,11.0,46500.0,NaN,NaN,NaN,NO_NEFT_TXN,NaN,NaN,NO_NEFT_TXN,NO_TPT_TXN,NO_TPT_TXN,NO_IMPS_TXN,311408.0,0.247852,N,N,Y,N,N,Y,N,Y,Y,N,38952.0,15200.0,19605.0,NONE,27163.10,49675.27,Y,Y,0.000000,N
4,23637,CSA,M,INDIVIDUAL,SALARIED,34,22260.94,6060.94,Y,Y,Y,Y,Y,Y,Y,Y,Y,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,88000.0,15660.04,21246.48,16483.54,0,6172.94,9099.94,15858.71,14008.08,4570.73,1.0,NaN,1.0,11.0,15094.78,21.0,16.0,7.0,16.0,8333.35,13.0,NaN,NaN,NaN,NaN,380.0,1.0,NaN,NaN,NaN,NaN,N,N,N,N,N,NONE,ENGINEER,N,N,0,18668.96,24565.91,4.0,7.0,14000.0,26931.60,29500.0,3.0,7.0,21500.0,13700.00,9264.0,4.0,1.0,5000.0,9817.25,6532.79,4.0,3.0,3580.0,37936.00,58018.00,4.0,5.0,29000.0,16200.00,1307.07,4.0,1.0,690.0,PQ_WITH_INCOME_20K,NaN,NaN,NO_NEFT_TXN,NaN,NaN,NO_NEFT_TXN,NO_TPT_TXN,NO_TPT_TXN,NOT_RELEVANT,122015,NaN,N,N,N,N,N,N,N,N,Y,N,0.0,0.0,0.0,NONE,21065.87,983.87,Y,Y,251.758794,N

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
for c in train.columns:
    if train[c].dtype == 'object' and c not in ['CUSTOMER_ID','RESPONDERS']:
        #print(c)
        lbl = LabelEncoder()
        lbl.fit(list(train[c].values) + list(test[c].values))
        train[c] = lbl.transform(list(train[c].values))
        test[c] = lbl.transform(list(test[c].values))

In [14]:
train['RESPONDERS'] = train['RESPONDERS'].replace(to_replace = {'Y':1, 'N':0})

In [99]:
## using xgb
import xgboost as xgb

In [50]:
target = train['RESPONDERS']

In [16]:
X_train = train.drop(['CUSTOMER_ID','RESPONDERS'], axis=1)
X_test = test.drop(['CUSTOMER_ID'], axis=1)

In [102]:
dtrain = xgb.DMatrix(X_train, label=target, missing=np.nan)
dtest = xgb.DMatrix(X_test, missing=np.nan)

In [105]:
params = {"objective": "binary:logistic","booster": "gbtree", "nthread": 4,
                "eta": 0.08, "max_depth": 6, "subsample": 0.9, "colsample_bytree": 0.7,
                "min_child_weight": 1,
                "seed": 2016, "tree_method": "exact"}

In [106]:
xgb_cv = xgb.cv(params, dtrain, num_boost_round=1000, nfold=10, stratified=True, metrics = 'auc', \
                maximize=True, early_stopping_rounds=40, verbose_eval=20)

[0]	train-auc:0.808265+0.0193653	test-auc:0.800576+0.0298709
[20]	train-auc:0.884257+0.000650901	test-auc:0.86348+0.00768839
[40]	train-auc:0.895515+0.00115678	test-auc:0.867766+0.00713257
[60]	train-auc:0.90812+0.000641188	test-auc:0.872018+0.00753577
[80]	train-auc:0.920671+0.000875873	test-auc:0.875272+0.00706395
[100]	train-auc:0.929954+0.000903114	test-auc:0.877539+0.00661461
[120]	train-auc:0.936799+0.000907468	test-auc:0.87832+0.00639875
[140]	train-auc:0.942709+0.00110743	test-auc:0.878586+0.0062563
[160]	train-auc:0.947686+0.00101072	test-auc:0.87887+0.00616765
[180]	train-auc:0.952115+0.00116316	test-auc:0.878908+0.00594
[200]	train-auc:0.955936+0.00105508	test-auc:0.878798+0.00581404

In [108]:
best_round = np.argmax(xgb_cv['test-auc-mean'])

In [109]:
xgb1 = xgb.train(params, dtrain, num_boost_round=best_round)

In [110]:
pred1 = xgb1.predict(dtest)

In [113]:
sub['RESPONDERS'] = pred1

In [114]:
sub.to_csv('submissions/xgb_baseline.csv', index=False) ##0.5643

### Model 3 - LightGBM

In [17]:
import lightgbm as lgb

In [18]:
ltrain = lgb.Dataset(X_train, label=target)
ltest = lgb.Dataset(X_test)

In [24]:
params = {
    
    'learning_rate':0.1,
    'max_depth':4,
    'boosting':'gbdt',
    'objective':'binary',
    'metric':'auc',
    'seed':2017,
    'feature_fraction':0.7,
    'bagging_fraction':0.7,
    'lambda_l1':1
}

In [25]:
mod1 = lgb.cv(params, ltrain, num_boost_round=1000, nfold=5, stratified=True, shuffle=True, early_stopping_rounds=40, verbose_eval=20)

[20]	cv_agg's auc: 0.855947 + 0.00706436
[40]	cv_agg's auc: 0.861496 + 0.00692191
[60]	cv_agg's auc: 0.867017 + 0.0068158
[80]	cv_agg's auc: 0.8711 + 0.00663687
[100]	cv_agg's auc: 0.872694 + 0.00650591
[120]	cv_agg's auc: 0.873851 + 0.00632846
[140]	cv_agg's auc: 0.874474 + 0.00613474
[160]	cv_agg's auc: 0.874936 + 0.0060923
[180]	cv_agg's auc: 0.87504 + 0.0061201
[200]	cv_agg's auc: 0.875161 + 0.00598024
[220]	cv_agg's auc: 0.875361 + 0.00580454
[240]	cv_agg's auc: 0.875395 + 0.00570537
[260]	cv_agg's auc: 0.875379 + 0.00559045
[280]	cv_agg's auc: 0.875589 + 0.00571636
[300]	cv_agg's auc: 0.875741 + 0.0054553
[320]	cv_agg's auc: 0.875691 + 0.00557883
[340]	cv_agg's auc: 0.875591 + 0.00533898

In [39]:
n_round = [v.index(max(v)) for k,v in mod1.items() if k == 'auc-mean'][0]

In [41]:
mod2 = lgb.train(params, ltrain, num_boost_round=n_round)

In [46]:
sub2 = mod2.predict(X_test)

In [49]:
sub = pd.DataFrame({'CUSTOMER_ID':test['CUSTOMER_ID'], 'RESPONDERS':sub2})
sub.to_csv('submissions/lgb_baseline.csv', index=False) ## 0.5526

### Running Second Model - Upsampling

In [ ]:
## upsample data in xgboost
from sklearn.model_selection import StratifiedKFold
kfold = 10
skf = StratifiedKFold(n_splits = 10, random_state = 2018)

for i, (train_index, test_index) in enumerate(skf.split(X_train, target)):
    print('[Fold: %d/%d]'%(i+1, kfold))
    X_train, X_valid = X_train.iloc[train_index], X_train.iloc[test_index]
    y_train, y_valid = y.iloc[train_index], y.iloc[test_index]
    
    if increase:
        pos = pd.Series(y_train == 1)
        
        X_train = pd.concat([X_train, X_train[pos]], axis=0)
        y_train = pd.concat([y_train, y_train.loc[pos]], axis=0)
        
        idx = np.arange(len(X_train))
        np.random.shuffle(idx)
        X_train = X_train.iloc[idx]
        y_train = y_train.iloc[idx]
        
    d_train = xgb.DMatrix(X_train, y_train, missing = np.nan)
    d_test = xgb.DMatrix(X_valid, y_valid, missing=np.nan)
    d_test = xgb.DMatrix(test)
    
    watchlist = [(d_train, 'train'),(d_valid, 'valid')]
    mdl = xgb.train(params, d_train, 2000, watchlist, early_stopping_round = 40, metric = 'auc', maximize=True, verbose_eval = 20)
    
    print('[Fold %d/%d Prediction: ]', %(i+1, kfold))
    
    p_test = mdl.predict(d_test, ntree_limit = mdl.best_ntree_limit)
    sub['RESPONDERS'] += p_test/kfold

In [52]:
## check feature importances

In [54]:
from sklearn.feature_selection import SelectKBest, chi2

In [62]:
for c in train.columns:
    if train[c].dtype == 'object' and train[c].isnull().any():
        train[c].fillna('MISSING', inplace=True)
        test[c].fillna('MISSING', inplace=True)
    elif (train[c].dtype == np.int64 or train[c].dtype == np.float64) and train[c].isnull().any():
        train[c].fillna(-1, inplace=True)
        test[c].fillna(-1, inplace=True)

In [64]:
train[''].value_counts()

0    213385
1     86615
Name: ACT_TYPE, dtype: int64